/**
 * Type-safe mock response builders
 *
 * Builds mock API responses using the autogenerated model types.
 * Each builder generates realistic default data that can be overridden.
 */

import type {
  User,
  Workshop,
  Trace,
  Rubric,
  Annotation,
  DiscoveryFinding,
  UserPermissions,
  AuthResponse,
} from '../types';
import { JudgeType, UserRole, UserStatus, WorkshopPhase, WorkshopStatus } from '../types';

// Counter for generating unique IDs
let idCounter = 0;

/**
 * Generate a UUID-like ID for mock data
 */
export function generateId(): string {
  idCounter++;
  const timestamp = Date.now().toString(16).padStart(12, '0');
  const counter = idCounter.toString(16).padStart(4, '0');
  const random1 = Math.random().toString(16).slice(2, 10).padEnd(8, '0');
  const random2 = Math.random().toString(16).slice(2, 10).padEnd(8, '0');
  return `${timestamp.slice(0, 8)}-${timestamp.slice(8, 12)}-4${counter.slice(1, 4)}-${random1.slice(0, 4)}-${random1.slice(4, 8)}${random2.slice(0, 4)}`;
}

/**
 * Reset the ID counter (useful between tests)
 */
export function resetIdCounter(): void {
  idCounter = 0;
}

/**
 * Build a mock User
 */
export class UserBuilder {
  private data: Partial<User> = {};

  constructor(role: UserRole = UserRole.PARTICIPANT) {
    this.data = {
      id: generateId(),
      email: `${role}-${idCounter}@test.com`,
      name: `Test ${role.charAt(0).toUpperCase() + role.slice(1)} ${idCounter}`,
      role,
      workshop_id: '',
      status: UserStatus.ACTIVE,
      created_at: new Date().toISOString(),
    };
  }

  withId(id: string): this {
    this.data.id = id;
    return this;
  }

  withEmail(email: string): this {
    this.data.email = email;
    return this;
  }

  withName(name: string): this {
    this.data.name = name;
    return this;
  }

  withRole(role: UserRole): this {
    this.data.role = role;
    return this;
  }

  withWorkshopId(workshopId: string): this {
    this.data.workshop_id = workshopId;
    return this;
  }

  withStatus(status: UserStatus): this {
    this.data.status = status;
    return this;
  }

  build(): User {
    return this.data as User;
  }
}

/**
 * Build a mock Workshop
 */
export class WorkshopBuilder {
  private data: Partial<Workshop> = {};

  constructor() {
    const id = generateId();
    this.data = {
      id,
      name: `Test Workshop ${idCounter}`,
      facilitator_id: '',
      status: WorkshopStatus.ACTIVE,
      current_phase: WorkshopPhase.INTAKE,
      completed_phases: [],
      discovery_started: false,
      annotation_started: false,
      active_discovery_trace_ids: [],
      active_annotation_trace_ids: [],
      created_at: new Date().toISOString(),
    };
  }

  withId(id: string): this {
    this.data.id = id;
    return this;
  }

  withName(name: string): this {
    this.data.name = name;
    return this;
  }

  withDescription(description: string): this {
    this.data.description = description;
    return this;
  }

  withFacilitatorId(facilitatorId: string): this {
    this.data.facilitator_id = facilitatorId;
    return this;
  }

  withPhase(phase: WorkshopPhase): this {
    this.data.current_phase = phase;
    // Update completed phases based on target phase
    const phases: WorkshopPhase[] = [
      WorkshopPhase.INTAKE,
      WorkshopPhase.DISCOVERY,
      WorkshopPhase.RUBRIC,
      WorkshopPhase.ANNOTATION,
      WorkshopPhase.RESULTS,
      WorkshopPhase.JUDGE_TUNING,
      WorkshopPhase.UNITY_VOLUME,
    ];
    const phaseIndex = phases.indexOf(phase);
    this.data.completed_phases = phases.slice(0, phaseIndex);

    // Update started flags
    if (phaseIndex >= 1) {
      this.data.discovery_started = true;
    }
    if (phaseIndex >= 3) {
      this.data.annotation_started = true;
    }

    return this;
  }

  withDiscoveryStarted(started: boolean): this {
    this.data.discovery_started = started;
    return this;
  }

  withAnnotationStarted(started: boolean): this {
    this.data.annotation_started = started;
    return this;
  }

  withActiveDiscoveryTraceIds(ids: string[]): this {
    this.data.active_discovery_trace_ids = ids;
    return this;
  }

  withActiveAnnotationTraceIds(ids: string[]): this {
    this.data.active_annotation_trace_ids = ids;
    return this;
  }

  build(): Workshop {
    return this.data as Workshop;
  }
}

/**
 * Build a mock Trace
 */
export class TraceBuilder {
  private data: Partial<Trace> = {};

  constructor(index: number = 0) {
    this.data = {
      id: generateId(),
      workshop_id: '',
      input: `User question ${index + 1}: How do I accomplish task ${index + 1}?`,
      output: `Assistant response ${index + 1}: Here's how you can accomplish task ${index + 1}. First, you should...`,
      context: { source: 'e2e-test', index },
      include_in_alignment: true,
      created_at: new Date().toISOString(),
    };
  }

  withId(id: string): this {
    this.data.id = id;
    return this;
  }

  withWorkshopId(workshopId: string): this {
    this.data.workshop_id = workshopId;
    return this;
  }

  withInput(input: string): this {
    this.data.input = input;
    return this;
  }

  withOutput(output: string): this {
    this.data.output = output;
    return this;
  }

  withContext(context: Record<string, unknown>): this {
    this.data.context = context;
    return this;
  }

  withMlflowTraceId(mlflowTraceId: string): this {
    this.data.mlflow_trace_id = mlflowTraceId;
    return this;
  }

  withSummary(summary: {
    executive_summary: string;
    milestones: Array<{
      number: number;
      title: string;
      summary: string;
      inputs: Array<{ span_name: string; field: 'inputs' | 'outputs'; value?: unknown }>;
      outputs: Array<{ span_name: string; field: 'inputs' | 'outputs'; value?: unknown }>;
    }>;
  }): this {
    (this.data as Record<string, unknown>).summary = summary;
    return this;
  }

  build(): Trace {
    return this.data as Trace;
  }
}

/**
 * Build a mock Rubric
 */
export class RubricBuilder {
  private data: Partial<Rubric> = {};

  constructor() {
    this.data = {
      id: generateId(),
      workshop_id: '',
      question: 'How helpful and accurate is this response?',
      judge_type: JudgeType.LIKERT,
      rating_scale: 5,
      created_by: '',
      created_at: new Date().toISOString(),
    };
  }

  withId(id: string): this {
    this.data.id = id;
    return this;
  }

  withWorkshopId(workshopId: string): this {
    this.data.workshop_id = workshopId;
    return this;
  }

  withQuestion(question: string): this {
    this.data.question = question;
    return this;
  }

  withJudgeType(judgeType: JudgeType): this {
    this.data.judge_type = judgeType;
    return this;
  }

  withRatingScale(scale: number): this {
    this.data.rating_scale = scale;
    return this;
  }

  withBinaryLabels(labels: Record<string, string>): this {
    this.data.binary_labels = labels;
    return this;
  }

  withCreatedBy(userId: string): this {
    this.data.created_by = userId;
    return this;
  }

  build(): Rubric {
    return this.data as Rubric;
  }
}

/**
 * Build a mock DiscoveryFinding
 */
export class FindingBuilder {
  private data: Partial<DiscoveryFinding> = {};

  constructor(index: number = 0) {
    this.data = {
      id: generateId(),
      workshop_id: '',
      trace_id: '',
      user_id: '',
      insight: `Finding ${index + 1}: The response was generally helpful but could be improved by providing more specific examples.`,
      created_at: new Date().toISOString(),
    };
  }

  withId(id: string): this {
    this.data.id = id;
    return this;
  }

  withWorkshopId(workshopId: string): this {
    this.data.workshop_id = workshopId;
    return this;
  }

  withTraceId(traceId: string): this {
    this.data.trace_id = traceId;
    return this;
  }

  withUserId(userId: string): this {
    this.data.user_id = userId;
    return this;
  }

  withInsight(insight: string): this {
    this.data.insight = insight;
    return this;
  }

  build(): DiscoveryFinding {
    return this.data as DiscoveryFinding;
  }
}

/**
 * Build a mock Annotation
 */
export class AnnotationBuilder {
  private data: Partial<Annotation> = {};

  constructor() {
    this.data = {
      id: generateId(),
      workshop_id: '',
      trace_id: '',
      user_id: '',
      rating: 4,
      created_at: new Date().toISOString(),
    };
  }

  withId(id: string): this {
    this.data.id = id;
    return this;
  }

  withWorkshopId(workshopId: string): this {
    this.data.workshop_id = workshopId;
    return this;
  }

  withTraceId(traceId: string): this {
    this.data.trace_id = traceId;
    return this;
  }

  withUserId(userId: string): this {
    this.data.user_id = userId;
    return this;
  }

  withRating(rating: number): this {
    this.data.rating = rating;
    return this;
  }

  withRatings(ratings: Record<string, number>): this {
    this.data.ratings = ratings;
    return this;
  }

  withComment(comment: string): this {
    this.data.comment = comment;
    return this;
  }

  build(): Annotation {
    return this.data as Annotation;
  }
}

/**
 * Build mock UserPermissions based on role
 */
export function buildPermissions(role: UserRole): UserPermissions {
  if (role === UserRole.FACILITATOR) {
    return {
      can_view_discovery: true,
      can_create_findings: false,
      can_view_all_findings: true,
      can_create_rubric: true,
      can_view_rubric: true,
      can_annotate: false,
      can_view_all_annotations: true,
      can_view_results: true,
      can_manage_workshop: true,
      can_assign_annotations: true,
    };
  } else if (role === UserRole.SME) {
    return {
      can_view_discovery: true,
      can_create_findings: true,
      can_view_all_findings: false,
      can_create_rubric: false,
      can_view_rubric: false,
      can_annotate: true,
      can_view_all_annotations: false,
      can_view_results: false,
      can_manage_workshop: false,
      can_assign_annotations: false,
    };
  } else {
    // participant
    return {
      can_view_discovery: true,
      can_create_findings: true,
      can_view_all_findings: false,
      can_create_rubric: false,
      can_view_rubric: false,
      can_annotate: true,
      can_view_all_annotations: false,
      can_view_results: false,
      can_manage_workshop: false,
      can_assign_annotations: false,
    };
  }
}

/**
 * Build a mock AuthResponse
 */
export function buildAuthResponse(
  user: User,
  isPreconfiguredFacilitator: boolean = false
): AuthResponse {
  return {
    user,
    is_preconfigured_facilitator: isPreconfiguredFacilitator,
    message: 'Login successful',
  };
}
