command:
  - "gunicorn"
  - "server.app:app"
  - "-c"
  - "gunicorn_conf.py"
  - "-w"
  - "2"
  - "--worker-class"
  - "uvicorn.workers.UvicornWorker"
  - "--timeout"
  - "1800"
env:
  - name: DATABASE_ENV
    value: postgres
  - name: APP_LOG_LEVEL
    value: INFO
  - name: TRACE_SUMMARIZATION_AGENT_TIMEOUT_S
    value: "120"
  - name: TRACE_SUMMARIZATION_MAX_CONCURRENCY
    value: "2"
  - name: MLFLOW_EXPERIMENT_ID
    valueFrom: experiment
  - name: ENDPOINT_NAME
    valueFrom: database