/**
 * E2E Test Infrastructure Types
 *
 * Re-exports types from the autogenerated client and defines
 * builder-specific types for the test infrastructure.
 */

import type { Page, Browser, BrowserContext } from '@playwright/test';

// Re-export types from autogenerated client
export type { User } from '../../src/client/models/User';
export { UserRole } from '../../src/client/models/UserRole';
export { UserStatus } from '../../src/client/models/UserStatus';
export type { UserCreate } from '../../src/client/models/UserCreate';
export type { UserPermissions } from '../../src/client/models/UserPermissions';
export type { AuthSession } from '../../src/client/models/AuthSession';
export { ProviderRole } from '../../src/client/models/ProviderRole';

export type { Workshop } from '../../src/client/models/Workshop';
export type { WorkshopCreate } from '../../src/client/models/WorkshopCreate';
export { WorkshopPhase } from '../../src/client/models/WorkshopPhase';
export { WorkshopStatus } from '../../src/client/models/WorkshopStatus';

export type { Trace } from '../../src/client/models/Trace';
export type { TraceUpload } from '../../src/client/models/TraceUpload';

export type { Rubric } from '../../src/client/models/Rubric';
export type { RubricCreate } from '../../src/client/models/RubricCreate';
export { JudgeType } from '../../src/client/models/JudgeType';

export type { Annotation } from '../../src/client/models/Annotation';
export type { AnnotationCreate } from '../../src/client/models/AnnotationCreate';

export type { DiscoveryFinding } from '../../src/client/models/DiscoveryFinding';
export type { DiscoveryFindingCreate } from '../../src/client/models/DiscoveryFindingCreate';

export type { IRRResult } from '../../src/client/models/IRRResult';

// Import concrete types for use in interfaces
import type { User } from '../../src/client/models/User';
import type { UserRole } from '../../src/client/models/UserRole';
import type { Workshop } from '../../src/client/models/Workshop';
import type { WorkshopPhase } from '../../src/client/models/WorkshopPhase';
import type { Trace } from '../../src/client/models/Trace';
import type { Rubric } from '../../src/client/models/Rubric';
import type { Annotation } from '../../src/client/models/Annotation';
import type { DiscoveryFinding } from '../../src/client/models/DiscoveryFinding';

/**
 * Configuration for creating a workshop in tests
 */
export interface WorkshopConfig {
  name?: string;
  description?: string;
}

/**
 * Configuration for creating a user in tests
 */
export interface UserConfig {
  email?: string;
  name?: string;
  password?: string;
}

/**
 * Configuration for creating a trace in tests
 */
export interface TraceConfig {
  input?: string;
  output?: string;
  context?: Record<string, unknown>;
}

/**
 * Configuration for creating a rubric in tests
 */
export interface RubricConfig {
  question?: string;
  judgeType?: import('../../src/client/models/JudgeType').JudgeType;
  ratingScale?: number;
  binaryLabels?: Record<string, string>;
}

/**
 * Configuration for creating a discovery finding in tests
 */
export interface FindingConfig {
  trace?: Trace;
  traceIndex?: number;
  insight?: string;
}

/**
 * Configuration for creating an annotation in tests
 */
export interface AnnotationConfig {
  trace?: Trace;
  traceIndex?: number;
  rating?: number;
  ratings?: Record<string, number>;
  comment?: string;
}

/**
 * Service names that can be mocked/made real
 */
export type ServiceName =
  | 'WorkshopsService'
  | 'UsersService'
  | 'DatabricksService'
  | 'DbsqlExportService';

/**
 * Users organized by role for easy access
 */
export interface UsersByRole {
  facilitator: User[];
  sme: User[];
  participant: User[];
}

/**
 * The result of building a test scenario
 */
export interface BuiltScenario {
  /** The Playwright page */
  page: Page;

  /** The browser (if multi-browser) */
  browser?: Browser;

  /** The workshop created for this scenario */
  workshop: Workshop;

  /** The facilitator user (first one if multiple) */
  facilitator: User;

  /** All users organized by role */
  users: UsersByRole;

  /** All traces created */
  traces: Trace[];

  /** The rubric if created */
  rubric?: Rubric;

  /** All findings created */
  findings: DiscoveryFinding[];

  /** All annotations created */
  annotations: Annotation[];

  // Actions
  loginAs(user: User): Promise<void>;
  logout(): Promise<void>;
  advanceToPhase(phase: WorkshopPhase): Promise<void>;
  beginDiscovery(traceLimit?: number): Promise<void>;
  beginAnnotation(): Promise<void>;
  goToPhase(phase: WorkshopPhase): Promise<void>;
  goToTab(tabName: string): Promise<void>;
  createRubricQuestion(config: RubricConfig): Promise<Rubric>;
  submitFinding(config: FindingConfig): Promise<DiscoveryFinding>;
  submitAnnotation(config: AnnotationConfig): Promise<Annotation>;
  completeDiscovery(): Promise<void>;

  // Multi-browser support
  newPageAs(user: User): Promise<Page>;
  using(page: Page): PageActions;

  // API access for assertions
  api: ScenarioApi;

  // Cleanup
  cleanup(): Promise<void>;
}

/**
 * Actions scoped to a specific page (for multi-browser tests)
 */
export interface PageActions {
  loginAs(user: User): Promise<void>;
  logout(): Promise<void>;
  beginDiscovery(traceLimit?: number): Promise<void>;
  beginAnnotation(): Promise<void>;
  goToPhase(phase: WorkshopPhase): Promise<void>;
  goToTab(tabName: string): Promise<void>;
  createRubricQuestion(config: RubricConfig): Promise<Rubric>;
  submitFinding(config: FindingConfig): Promise<DiscoveryFinding>;
  submitAnnotation(config: AnnotationConfig): Promise<Annotation>;
  completeDiscovery(): Promise<void>;
}

/**
 * API access for making direct API calls in tests
 */
export interface ScenarioApi {
  getWorkshop(): Promise<Workshop>;
  getRubric(): Promise<Rubric | null>;
  getTraces(): Promise<Trace[]>;
  getFindings(userId?: string): Promise<DiscoveryFinding[]>;
  getAnnotations(userId?: string): Promise<Annotation[]>;
  getDiscoveryCompletionStatus(): Promise<{
    total_participants: number;
    completed_participants: number;
    all_completed: boolean;
  }>;
}

/**
 * Internal builder state
 */
export interface BuilderState {
  // Page/browser
  page?: Page;
  browser?: Browser;

  // Mock configuration
  mockAll: boolean;
  realServices: Set<string>;
  realEndpoints: Set<string>;

  // Workshop config
  workshopConfig?: WorkshopConfig;

  // Users to create
  facilitatorConfig?: UserConfig;
  participantConfigs: UserConfig[];
  smeConfigs: UserConfig[];
  additionalUsers: Array<{ role: UserRole; config: UserConfig }>;

  // Data to create
  traceCount: number;
  traceConfigs: TraceConfig[];
  rubricConfig?: RubricConfig;
  findingConfigs: FindingConfig[];
  annotationConfigs: AnnotationConfig[];

  // Phase
  targetPhase?: WorkshopPhase;

  // Flags
  discoveryComplete: boolean;
}
